// Generated by Wrangler on Sat Sep 21 2024 14:07:36 GMT+0800 (Hong Kong Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	MY_PERSONAL_FIN_DB: D1Database;
}
